<script type="text/javascript">
    require(['jquery'], function($){
        "use strict";
        $(function(){
            Opentip.styles.slick = {

            };
            $('.tpl-hint').each(function(){
                var id = $(this).attr('id');
                $(this).on('mouseover', function(event){
                    event.stopPropagation();
                    event.preventDefault();
                    console.log('#' + id + '-infobox');
                    new Opentip(
                        this,
                        $('#' + id + '-infobox').html(),
                        $('#' + id + '-title').html(),
                        {
                            style: 'slick',
                            hideOn: 'click',
                            offset: [-10, -10],
                            fixed: true,
                            group: 'ath'
                        }
                    )
                })
            })
        });
    });
</script>